// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/data.ts
import matter from "npm:gray-matter@^4.0.3";

// content/site.json
var site_default = {
  name: "Aman Mishra",
  role: "Senior Product Designer",
  location: "Bengaluru, India",
  email: "hello@amanmishra.design",
  resumeUrl: "/resume.pdf",
  socials: {
    linkedin: "https://linkedin.com/in/amanmishra",
    twitter: "https://twitter.com/amanmishra",
    read: "https://read.cv/amanmishra",
    github: "https://github.com/amanmishra"
  },
  tagline: "Designing thoughtful digital products through research, systems thinking, and interaction craft.",
  availability: "Open to Senior Product Designer roles"
};

// content/experience.json
var experience_default = {
  roles: [
    {
      role: "Senior Product Designer",
      company: "Razorpay",
      period: "2023 \u2014 Present",
      summary: "Leading design for merchant onboarding and risk. Built the Blitz design system now used across 6 product surfaces."
    },
    {
      role: "Product Designer",
      company: "CRED",
      period: "2021 \u2014 2023",
      summary: "Owned end-to-end design for credit card management. Shipped features touching 4M+ MAUs."
    },
    {
      role: "Product Designer",
      company: "Zeta",
      period: "2020 \u2014 2021",
      summary: "Enterprise banking flows. Cut onboarding drop-off from 41% to 17% through research-led iteration."
    },
    {
      role: "Design Intern",
      company: "Freshworks",
      period: "2019 \u2014 2020",
      summary: "First real design job. Learned how systems, patterns, and constraints compose good products."
    }
  ]
};

// content/skills.json
var skills_default = {
  groups: [
    {
      group: "Craft",
      items: ["Interaction design", "Visual design", "Prototyping", "Motion", "Design systems", "Accessibility"]
    },
    {
      group: "Process",
      items: ["User research", "Jobs-to-be-done", "Service blueprints", "Information architecture", "Usability testing", "Metrics-informed design"]
    },
    {
      group: "Tools",
      items: ["Figma", "Principle", "Framer", "Rive", "Notion", "Linear", "Amplitude", "Maze"]
    }
  ]
};

// src/lib/mcp/data.ts
var rawProjects = import.meta.glob("../../../content/projects/*/index.mdx", {
  eager: true,
  query: "?raw",
  import: "default"
});
function slugFromPath(path) {
  return path.match(/\/projects\/([^/]+)\/index\.mdx$/)?.[1] ?? "";
}
var parsed = Object.entries(rawProjects).map(([path, raw]) => {
  const { data, content } = matter(raw);
  const slug = data.slug ?? slugFromPath(path);
  return {
    slug,
    title: data.title ?? slug,
    company: data.company ?? "",
    role: data.role ?? "",
    duration: data.duration ?? "",
    timeline: data.timeline ?? "",
    category: data.category ?? "",
    summary: data.summary ?? "",
    featured: Boolean(data.featured),
    order: typeof data.order === "number" ? data.order : 99,
    metrics: Array.isArray(data.metrics) ? data.metrics : [],
    team: Array.isArray(data.team) ? data.team : [],
    constraints: Array.isArray(data.constraints) ? data.constraints : [],
    url: `https://amanmishra.design/projects/${slug}`,
    body: content.trim()
  };
});
var projects = parsed.sort((a, b) => a.order - b.order);
function toSummary(p) {
  const { body, ...rest } = p;
  void body;
  return rest;
}
var siteInfo = site_default;
var experience = experience_default.roles;
var skills = skills_default.groups;

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List case studies",
  description: "List Aman Mishra's product design case studies with title, company, role, category, summary, key metrics, and a link.",
  inputSchema: {
    featuredOnly: z.boolean().optional().describe("If true, return only projects marked as featured.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ featuredOnly }) => {
    const items = (featuredOnly ? projects.filter((p) => p.featured) : projects).map(
      toSummary
    );
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get case study",
  description: "Return the full case study for a given slug, including the MDX body content, metrics, team, constraints, and public URL.",
  inputSchema: {
    slug: z2.string().min(1).describe("The project slug, e.g. 'meera-ai'. Use list_projects to discover slugs.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const project = projects.find((p) => p.slug === slug);
    if (!project) {
      return {
        content: [{ type: "text", text: `No project found with slug "${slug}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/get-about.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_about_default = defineTool3({
  name: "get_about",
  title: "About Aman Mishra",
  description: "Return a concise profile: name, current role, location, tagline, availability, social links, and skill groups.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const about = { ...siteInfo, skills };
    return {
      content: [{ type: "text", text: JSON.stringify(about, null, 2) }],
      structuredContent: { about }
    };
  }
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_experience_default = defineTool4({
  name: "get_experience",
  title: "Work experience",
  description: "Return Aman Mishra's work experience \u2014 roles, companies, timelines, and highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/contact-inquiry.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function getSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("Backend is not configured.");
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
var contact_inquiry_default = defineTool5({
  name: "contact_inquiry",
  title: "Submit a contact inquiry",
  description: "Send a message to Aman Mishra on the visitor's behalf. Use only when the visitor has explicitly asked to contact him. Include the visitor's own name, email, and message \u2014 never invented values.",
  inputSchema: {
    name: z3.string().trim().min(1).max(200).describe("Visitor's full name."),
    email: z3.string().trim().email().max(320).describe("Visitor's email address."),
    message: z3.string().trim().min(1).max(5e3).describe("The message to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, message }) => {
    try {
      const supabase = getSupabase();
      const { error } = await supabase.from("contact_inquiries").insert({ name, email, message, source: "mcp" });
      if (error) {
        return {
          content: [{ type: "text", text: `Could not send: ${error.message}` }],
          isError: true
        };
      }
      return {
        content: [
          {
            type: "text",
            text: `Thanks \u2014 your message was delivered to Aman. He'll reply to ${email}.`
          }
        ],
        structuredContent: { delivered: true }
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      return { content: [{ type: "text", text: msg }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "aman-mishra-portfolio",
  title: "Aman Mishra \u2014 Portfolio",
  version: "0.1.0",
  instructions: "Tools for exploring Aman Mishra's product design portfolio. Use list_projects and get_project to reference case studies, get_about and get_experience for background, and contact_inquiry only when a visitor explicitly asks to contact him.",
  tools: [list_projects_default, get_project_default, get_about_default, get_experience_default, contact_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
